import { Prisma } from '@prisma/client';
export declare function findConversations(userId: number, page?: number, pageSize?: number): Promise<{
    list: {
        userId: number;
        nickname: string;
        username: string;
        avatarUrl: string;
        lastMessage: string;
        lastType: string;
        lastTime: string;
        unread: number;
        isMine: boolean;
        isRead: boolean;
        readAt: string | null;
    }[];
    total: number;
}>;
export declare function findMessages(userId: number, peerId: number, page?: number, pageSize?: number): Promise<[{
    id: number;
    type: string;
    content: string;
    isRead: boolean;
    createdAt: Date;
    replyToId: number | null;
    voiceDuration: number | null;
    fileName: string | null;
    fileSize: number | null;
    latitude: number | null;
    longitude: number | null;
    locationName: string | null;
    cardUserId: number | null;
    senderId: number;
    receiverId: number;
    imageStatus: string | null;
    isDelivered: boolean;
    readAt: Date | null;
    recalledAt: Date | null;
    voiceUrl: string | null;
    fileUrl: string | null;
}[], number]>;
export declare function markMessagesRead(senderId: number, receiverId: number): Promise<Prisma.BatchPayload>;
export declare function createMessage(data: {
    senderId: number;
    receiverId: number;
    content: string;
    type?: string;
}): Promise<{
    id: number;
    type: string;
    content: string;
    isRead: boolean;
    createdAt: Date;
    replyToId: number | null;
    voiceDuration: number | null;
    fileName: string | null;
    fileSize: number | null;
    latitude: number | null;
    longitude: number | null;
    locationName: string | null;
    cardUserId: number | null;
    senderId: number;
    receiverId: number;
    imageStatus: string | null;
    isDelivered: boolean;
    readAt: Date | null;
    recalledAt: Date | null;
    voiceUrl: string | null;
    fileUrl: string | null;
}>;
export declare function findMessageById(id: number): Promise<{
    id: number;
    type: string;
    content: string;
    isRead: boolean;
    createdAt: Date;
    replyToId: number | null;
    voiceDuration: number | null;
    fileName: string | null;
    fileSize: number | null;
    latitude: number | null;
    longitude: number | null;
    locationName: string | null;
    cardUserId: number | null;
    senderId: number;
    receiverId: number;
    imageStatus: string | null;
    isDelivered: boolean;
    readAt: Date | null;
    recalledAt: Date | null;
    voiceUrl: string | null;
    fileUrl: string | null;
} | null>;
export declare function recallMessage(id: number): Promise<{
    id: number;
    type: string;
    content: string;
    isRead: boolean;
    createdAt: Date;
    replyToId: number | null;
    voiceDuration: number | null;
    fileName: string | null;
    fileSize: number | null;
    latitude: number | null;
    longitude: number | null;
    locationName: string | null;
    cardUserId: number | null;
    senderId: number;
    receiverId: number;
    imageStatus: string | null;
    isDelivered: boolean;
    readAt: Date | null;
    recalledAt: Date | null;
    voiceUrl: string | null;
    fileUrl: string | null;
}>;
export declare function markMessageRead(id: number): Promise<{
    id: number;
    type: string;
    content: string;
    isRead: boolean;
    createdAt: Date;
    replyToId: number | null;
    voiceDuration: number | null;
    fileName: string | null;
    fileSize: number | null;
    latitude: number | null;
    longitude: number | null;
    locationName: string | null;
    cardUserId: number | null;
    senderId: number;
    receiverId: number;
    imageStatus: string | null;
    isDelivered: boolean;
    readAt: Date | null;
    recalledAt: Date | null;
    voiceUrl: string | null;
    fileUrl: string | null;
}>;
export declare function markMessageDelivered(id: number): Promise<{
    id: number;
    type: string;
    content: string;
    isRead: boolean;
    createdAt: Date;
    replyToId: number | null;
    voiceDuration: number | null;
    fileName: string | null;
    fileSize: number | null;
    latitude: number | null;
    longitude: number | null;
    locationName: string | null;
    cardUserId: number | null;
    senderId: number;
    receiverId: number;
    imageStatus: string | null;
    isDelivered: boolean;
    readAt: Date | null;
    recalledAt: Date | null;
    voiceUrl: string | null;
    fileUrl: string | null;
}>;
export declare function deleteMessages(ids: number[], userId: number): Promise<Prisma.BatchPayload>;
export declare function getUnreadCount(userId: number): Promise<number>;
export declare function countUserMessages(userId: number, peerId: number): Promise<number>;
export declare function findExistingUnreadCount(senderId: number, receiverId: number): Promise<number>;
export declare function getConversationSetting(userId: number, peerId: number): Promise<{
    userId: number;
    id: number;
    createdAt: Date;
    updatedAt: Date;
    isPinned: boolean;
    isMuted: boolean;
    muteUntil: Date | null;
    peerId: number;
    bgImage: string | null;
} | null>;
export declare function upsertConversationSetting(userId: number, peerId: number, data: {
    isPinned?: boolean;
    isMuted?: boolean;
    bgImage?: string;
}): Promise<{
    userId: number;
    id: number;
    createdAt: Date;
    updatedAt: Date;
    isPinned: boolean;
    isMuted: boolean;
    muteUntil: Date | null;
    peerId: number;
    bgImage: string | null;
}>;
export declare function checkBlocked(userId1: number, userId2: number): Promise<{
    id: number;
    createdAt: Date;
    blockerId: number;
    blockedId: number;
} | null>;
export declare function checkMutualFollow(userId1: number, userId2: number): Promise<boolean>;
//# sourceMappingURL=message.service.d.ts.map